# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - releases/*
  paths:
    include:
    - baffis.FrontEnd.Web

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build and Push
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'VisualStudioEnterpriseSubscription'
        repository: 'baffis.FrontEnd.Web'
        command: 'buildAndPush'
        Dockerfile: 'baffis.FrontEnd.Web/Dockerfile'
        buildContext: './'
