# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/baffis.FrontEnd.Web/ClientApp/Dockerfile'
        tags: |
          $(tag)

- stage: Push
  dependsOn: Build
  displayName: Push image
  jobs:
  - job: BuildAndPush
    displayName: Build And Push
    pool:
      vmImage: ubuntu-latest
    steps:    
    - task: Docker@2
      
      inputs:
        containerRegistry: 'VisualStudioEnterpriseSubscription'
        repository: 'startupstackdemocllddnxmjvpw2'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/baffis.FrontEnd.Web/ClientApp/Dockerfile'
