version: '3.4'

services:
  baffis.frontend.web:
    image: ${DOCKER_REGISTRY-}baffisfrontendweb
    build:
      context: .
      dockerfile: baffis.FrontEnd.Web/Dockerfile

  baffis.frontend.app:
    image: ${DOCKER_REGISTRY-}baffisfrontendapp
    build:
      context: .
      dockerfile: baffis.FrontEnd.Web/ClientApp/Dockerfile
    ports:
      - "4200:4200" 
      - "49153:49153"
    volumes:
      - ./baffis.FrontEnd.Web/ClientApp:/app

  baffis.service.rest:
    image: ${DOCKER_REGISTRY-}baffisservicerest
    build:
      context: .
      dockerfile: baffis.Service.Rest/Dockerfile


  baffis.service.stripeconnection:
    image: ${DOCKER_REGISTRY-}baffisservicestripeconnection
    build:
      context: .
      dockerfile: baffis.Service.StripeConnection/Dockerfile

  baffis.db:
    image: postgres:13
  adminer:
    image: adminer
  pgadmin:
    image: dpage/pgadmin4:6  
volumes:    
  odoo-db-data:

