version: '3.4'

services:
  baffis.frontend.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "44340:80"
      - "44341:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - baffis.frontend.app
  baffis.frontend.app:
    ports:
      - "4200:4200" 
      - "49153:49153"
    volumes:
      - ./baffis.FrontEnd.Web/ClientApp:/app
    depends_on:
      - baffis.db
  baffis.service.rest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "44330:80"
      - "44333:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  baffis.service.stripeconnection:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "44380:80"
      - "44387:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  baffis.db:
    environment:
      - POSTGRES_DB=BaffisDB
      - POSTGRES_PASSWORD=baffispassword
      - POSTGRES_USER=baffisuser
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./database/scripts:/docker-entrypoint-initdb.d/
  adminer:
    restart: always
    ports:
      - 8080:8080
  pgadmin:
    restart: always
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@baffis.com
      - PGADMIN_DEFAULT_PASSWORD=baffispassword   
