# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=BaffisDB
      - POSTGRES_PASSWORD=baffispassword
      - POSTGRES_USER=baffisuser
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./scripts:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  pgadmin:
    image: dpage/pgadmin4:6
    restart: always
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@baffis.com
      - PGADMIN_DEFAULT_PASSWORD=baffispassword   

volumes:    
  odoo-db-data: