name: .NET

on:
  push:
    branches: [ master ]
    paths:
    - baffis.Service.StripeConnection/**
  pull_request:
    branches: [ master ]
    paths:
    - baffis.Service.StripeConnection/**


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore baffis.Service.StripeConnection
    - name: Build
      run: dotnet build baffis.Service.StripeConnection --no-restore 
    - name: Test
      run: dotnet test baffis.Service.StripeConnection --no-build --verbosity normal
